name: Flutter Test

on:
  push:
    branches:
      - develop # developブランチに対してPRが作成された場合にトリガーされます

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Flutterプロジェクトをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # Flutter SDKをインストール
      - name: Install Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # プロジェクトの依存関係をインストール
      - name: Install dependencies
        run: flutter pub get

      # widgetテストの実行
      - name: Run widget tests
        run: flutter test

      # ユニットテストの実行
      - name: Run unit tests
        run: flutter test test/unit_test/

      # 統合テストの実行（iOSやAndroidエミュレータの設定が必要）
      # - name: Run integration tests
      #   run: |-
      #     sudo apt-get update -y
      #     sudo apt-get install -y ninja-build libgtk-3-dev
      #     flutter drive -d linux --target=test_driver/app.dart

      # 統合テスト後にテスト結果のログやスクリーンショットをアップロード
      - name: Upload test results (if any)
        if: success()
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "2922mpay@gmail.com"
          git remote set-url origin https://NittaMasayo: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@github.com/NittaMasayo/memory_game
          git fetch
          git checkout main
          git merge develop
          git push origin main
